version: '3.3'
services:
    computeA_20g:
        container_name: ${CONTAINERNAMEA}
        command: ["-vnc"]
        hostname: ${HOSTNAMEA}
        user: matlab
        environment:
          - MLM_LICENSE_FILE=${LICENSESERVER}
          - HOST=${HOSTNAMEA}
          - CUDA_VISIBLE_DEVICES=${CUDAA20g}
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu]
        volumes:
          - '/path_on_host/srv:/srv'
        ports:
            - ${VNCPORTA}:5901
            - ${WEBPORTA}:6080
        image: ${BASEIMAGE}
        shm_size: '512M'
        restart: unless-stopped
        
    computeB_20g:
        container_name: ${CONTAINERNAMEB}
        command: ["-vnc"]
        hostname: ${HOSTNAMEB}
        user: matlab
        environment:
          - MLM_LICENSE_FILE=${LICENSESERVER}
          - HOST=${HOSTNAMEB}
          - CUDA_VISIBLE_DEVICES=${CUDAB20g}
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu]
        volumes:
            - '/path_on_host/srv:/srv'
        ports:
            - ${VNCPORTB}:5901
            - ${WEBPORTB}:6080
        image: ${BASEIMAGE}
        shm_size: '512M'
        restart: unless-stopped
        
    computeC_20g:
        container_name: ${CONTAINERNAMEC}
        command: ["-vnc"]
        hostname: ${HOSTNAMEC}
        user: matlab
        environment:
          - MLM_LICENSE_FILE=${LICENSESERVER}
          - HOST=${HOSTNAMEC}
          - CUDA_VISIBLE_DEVICES=${CUDAC20g}
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu]
        volumes:
            - '/path_on_host/srv:/srv'
        ports:
            - ${VNCPORTC}:5901
            - ${WEBPORTC}:6080
        image: ${BASEIMAGE}
        shm_size: '512M'
        restart: unless-stopped
        
    computeD_10g:
        container_name: ${CONTAINERNAMED}
        command: ["-vnc"]
        hostname: ${HOSTNAMED}
        user: matlab
        environment:
          - MLM_LICENSE_FILE=${LICENSESERVER}
          - HOST=${HOSTNAMED}
          - CUDA_VISIBLE_DEVICES=${CUDAD10g}
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu]
        volumes:
            - '/path_on_host/srv:/srv'
        ports:
            - ${VNCPORTD}:5901
            - ${WEBPORTD}:6080
        image: ${BASEIMAGE}
        shm_size: '512M'
        restart: unless-stopped